qsub -v "size=75, foldnum=1" pbs/time_kfold_train.pbs
qsub -v "size=75, foldnum=2" pbs/time_kfold_train.pbs
qsub -v "size=75, foldnum=3" pbs/time_kfold_train.pbs
qsub -v "size=75, foldnum=4" pbs/time_kfold_train.pbs
qsub -v "size=75, foldnum=5" pbs/time_kfold_train.pbs
qsub -v "size=75, foldnum=1" pbs/time_kfold_train.pbs
qsub -v "size=75, foldnum=2" pbs/time_kfold_train.pbs
qsub -v "size=75, foldnum=3" pbs/time_kfold_train.pbs
qsub -v "size=75, foldnum=4" pbs/time_kfold_train.pbs
qsub -v "size=75, foldnum=5" pbs/time_kfold_train.pbs
qsub -v "size=75, foldnum=1" pbs/time_kfold_train.pbs
qsub -v "size=75, foldnum=2" pbs/time_kfold_train.pbs
qsub -v "size=75, foldnum=3" pbs/time_kfold_train.pbs
qsub -v "size=75, foldnum=4" pbs/time_kfold_train.pbs
qsub -v "size=75, foldnum=5" pbs/time_kfold_train.pbs
qsub -v "size=75, foldnum=1" pbs/time_kfold_train.pbs
qsub -v "size=75, foldnum=2" pbs/time_kfold_train.pbs
qsub -v "size=75, foldnum=3" pbs/time_kfold_train.pbs
qsub -v "size=75, foldnum=4" pbs/time_kfold_train.pbs
qsub -v "size=75, foldnum=5" pbs/time_kfold_train.pbs
qsub -v "size=75, foldnum=1" pbs/time_kfold_train.pbs
qsub -v "size=75, foldnum=2" pbs/time_kfold_train.pbs
qsub -v "size=75, foldnum=3" pbs/time_kfold_train.pbs
qsub -v "size=75, foldnum=4" pbs/time_kfold_train.pbs
qsub -v "size=75, foldnum=5" pbs/time_kfold_train.pbs