qsub -v "datadir=/scratch1/basill/data/cutnorm_15/, modeldir=/scratch1/basill/models_kfold_15/, windowsize=15" pbs/kfold_test.pbs
qsub -v "datadir=/scratch1/basill/data/cutnorm_30/, modeldir=/scratch1/basill/models_kfold_30/, windowsize=30" pbs/kfold_test.pbs
qsub -v "datadir=/scratch1/basill/data/cutnorm_45/, modeldir=/scratch1/basill/models_kfold_45/, windowsize=45" pbs/kfold_test.pbs
qsub -v "datadir=/scratch1/basill/data/cutnorm_60/, modeldir=/scratch1/basill/models_kfold_60/, windowsize=60" pbs/kfold_test.pbs
qsub -v "datadir=/scratch1/basill/data/cutnorm_75/, modeldir=/scratch1/basill/models_kfold_75/, windowsize=75" pbs/kfold_test.pbs
qsub -v "datadir=/scratch1/basill/data/cutnorm_90/, modeldir=/scratch1/basill/models_kfold_90/, windowsize=90" pbs/kfold_test.pbs
qsub -v "datadir=/scratch1/basill/data/cutnorm_105/, modeldir=/scratch1/basill/models_kfold_105/, windowsize=105" pbs/kfold_test.pbs
qsub -v "datadir=/scratch1/basill/data/cutnorm_120/, modeldir=/scratch1/basill/models_kfold_120/, windowsize=120" pbs/kfold_test.pbs
qsub -v "datadir=/scratch1/basill/data/cutnorm_135/, modeldir=/scratch1/basill/models_kfold_135/, windowsize=135" pbs/kfold_test.pbs
qsub -v "datadir=/scratch1/basill/data/cutnorm_150/, modeldir=/scratch1/basill/models_kfold_150/, windowsize=150" pbs/kfold_test.pbs