qsub -v "size=15, foldnum=5" pbs/kfold_train.pbs
qsub -v "size=30, foldnum=5" pbs/kfold_train.pbs
qsub -v "size=45, foldnum=5" pbs/kfold_train.pbs
qsub -v "size=60, foldnum=5" pbs/kfold_train.pbs
qsub -v "size=75, foldnum=5" pbs/kfold_train.pbs
qsub -v "size=90, foldnum=5" pbs/kfold_train.pbs
qsub -v "size=105, foldnum=5" pbs/kfold_train.pbs
qsub -v "size=120, foldnum=5" pbs/kfold_train.pbs
qsub -v "size=135, foldnum=5" pbs/kfold_train.pbs
qsub -v "size=150, foldnum=5" pbs/kfold_train.pbs