#PBS -N all_test
#PBS -l select=1:ncpus=8:mem=100gb:ngpus=1:gpu_model=p100,walltime=6:00:00
#PBS -n ${SIZE}_${STRIDE}_${MODEL}_${OUT}

# usage warning
module load cuda/10.2.89-gcc/8.3.1 cudnn/8.0.0.180-10.2-linux-x64-gcc/8.3.1 anaconda3/2019.10-gcc/8.3.1
CONDA_BASE=$(conda info --base)
source $CONDA_BASE/etc/profile.d/conda.sh
conda activate tf_env

cd pedometer/training/
./all_test.sh ../PedometerData ${SIZE} ${STRIDE} ${MODEL} 0 ${OUT}
