./cutnorm.sh ../PedometerData 15 1 0 &> /dev/null &
./cutnorm.sh ../PedometerData 30 1 0 &> /dev/null &
./cutnorm.sh ../PedometerData 45 1 0 &> /dev/null &
./cutnorm.sh ../PedometerData 60 1 0 &> /dev/null &
./cutnorm.sh ../PedometerData 75 1 0 &> /dev/null &
./cutnorm.sh ../PedometerData 90 1 0 &> /dev/null &
./cutnorm.sh ../PedometerData 105 1 0 &> /dev/null &
./cutnorm.sh ../PedometerData 120 1 0 &> /dev/null &
./cutnorm.sh ../PedometerData 135 1 0 &> /dev/null &
./cutnorm.sh ../PedometerData 150 1 0 &> /dev/null &