#/bin/bash
#PBS -N basill_1_test
#PBS -l select=1:ncpus=16:mem=125gb:ngpus=1:gpu_model=k20
#PBS -l walltime=72:00:00
#PBS -e /home/basill/pedometer/palmetto/job_output
#PBS -o /home/basill/pedometer/palmetto/job_output

module load cuda/10.2.89-gcc/8.3.1 cudnn/8.0.0.180-10.2-linux-x64-gcc/8.3.1 anaconda3/2019.10-gcc/8.3.1

source activate tf_env
cd
cd pedometer/window_test/

./1_test.sh /scratch1/basill/data/ /scratch1/basill/models/training_Regular_1 /scratch1/basill/PedometerData/ training_Regular_1_model_results.csv
